version: '3'
services:
  postgres:
    image: 'postgres:alpine3.16'
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: "./backend"
      args:
        - MIX_ENV=test
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_DB: $POSTGRES_DB
      TEST_POSTGRES_USER: $TEST_POSTGRES_USER
      TEST_POSTGRES_PASSWORD: $TEST_POSTGRES_PASSWORD
      TEST_POSTGRES_HOST: postgres
      TEST_POSTGRES_DB: $TEST_POSTGRES_DB
      SECRET_KEY: $SECRET_KEY
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    container_name: backend
    hostname: backend
    ports:
      - 4000:4000
    depends_on:
      - postgres
  frontend:
    build:
      context: "./frontend"
    container_name: frontend
    hostname: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
volumes:
  db-data:
    driver: local
